2024-09-29 21:42:06,419 | INFO | "test_run" выполнен успешно
2024-09-29 21:42:06,420 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\s4vel\Desktop\python\test_12_1\TestRunner.py", line 25, in test_run
    men = Runner(777)
          ^^^^^^^^^^^
  File "C:\Users\s4vel\Desktop\python\test_12_1\tests_12_4.py", line 9, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-29 21:42:06,422 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\s4vel\Desktop\python\test_12_1\TestRunner.py", line 12, in test_walk
    boy = Runner('boy', -5)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\s4vel\Desktop\python\test_12_1\tests_12_4.py", line 14, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
